TEAM_COLORS = {
    2022: {
        "Red Bull": "#004CFF",
        "Mercedes": "#00D2BE",
        "McLaren": "#EAA100",
        "Ferrari": "#DC0000",
        "Alpha Tauri": "#364165",
        "Aston Martin": "#3F8179",
        "Alpine": "#E791CE",
        "Alfa Romeo": "#800D00",
        "Williams": "#00A3E0",
        "Haas": "#ED1A3B",
    },
    2021: {
        "Red Bull": "#004CFF",
        "Mercedes": "#00D2BE",
        "McLaren": "#EAA100",
        "Ferrari": "#DC0000",
        "Alpha Tauri": "#364165",
        "Aston Martin": "#336F60",
        "Alpine": "#0090FF",
        "Alfa Romeo": "#800D00",
        "Williams": "#0463C0",
        "Haas": "#FFFFFF",
    },
    2020: {
        "Red Bull": "#004CFF",
        "Mercedes": "#00D2BE",
        "McLaren": "#EAA100",
        "Ferrari": "#DC0000",
        "Alpha Tauri": "#364165",
        "Racing Point": "#E791CE",
        "Renault": "#FAF230",
        "Alfa Romeo": "#800D00",
        "Williams": "#0463C0",
        "Haas": "#75747C",
    },
    2019: {
        "Red Bull": "#004CFF",
        "Mercedes": "#00D2BE",
        "McLaren": "#EAA100",
        "Ferrari": "#DC0000",
        "Toro Rosso": "#364165",
        "Racing Point": "#E791CE",
        "Renault": "#FAF230",
        "Alfa Romeo": "#800D00",
        "Williams": "#0463C0",
        "Haas": "#75747C",
    },
}

DRIVER_PERSONAL_COLORS = {
    "VER": "#FF5F1F",
    "HAM": "#6200EE",
    "NOR": "#FCF800",
    "PER": "#4CAF50",
    "BOT": "#008AD3",
}

DRIVER_TEAM = {
    2022: {
        "HAM": "Mercedes",
        "RUS": "Mercedes",
        "VER": "Red Bull",
        "PER": "Red Bull",
        "LEC": "Ferrari",
        "SAI": "Ferrari",
        "ALO": "Alpine",
        "OCO": "Alpine",
        "NOR": "McLaren",
        "RIC": "McLaren",
        "VET": "Aston Martin",
        "HUL": "Aston Martin",
        "STR": "Aston Martin",
        "BOT": "Alfa Romeo",
        "ZHO": "Alfa Romeo",
        "GAS": "Alpha Tauri",
        "TSU": "Alpha Tauri",
        "MSC": "Haas",
        "MAG": "Haas",
        "ALB": "Williams",
        "LAT": "Williams",
    },
    2021: {
        "HAM": "Mercedes",
        "BOT": "Mercedes",
        "VER": "Red Bull",
        "PER": "Red Bull",
        "LEC": "Ferrari",
        "SAI": "Ferrari",
        "ALO": "Alpine",
        "OCO": "Alpine",
        "NOR": "McLaren",
        "RIC": "McLaren",
        "VET": "Aston Martin",
        "STR": "Aston Martin",
        "RAI": "Alfa Romeo",
        "GIO": "Alfa Romeo",
        "KUB": "Alfa Romeo",
        "GAS": "Alpha Tauri",
        "TSU": "Alpha Tauri",
        "MSC": "Haas",
        "MAZ": "Haas",
        "RUS": "Williams",
        "LAT": "Williams",
    },
    2020: {
        "HAM": "Mercedes",
        "BOT": "Mercedes",
        "VER": "Red Bull",
        "ALB": "Red Bull",
        "LEC": "Ferrari",
        "VET": "Ferrari",
        "RIC": "Renault",
        "OCO": "Renault",
        "NOR": "McLaren",
        "SAI": "McLaren",
        "PER": "Racing Point",
        "STR": "Racing Point",
        "HUL": "Racing Point",
        "RAI": "Alfa Romeo",
        "GIO": "Alfa Romeo",
        "GAS": "Alpha Tauri",
        "KVY": "Alpha Tauri",
        "MAG": "Haas",
        "GRO": "Haas",
        "FIT": "Haas",
        "RUS": "Williams",
        "LAT": "Williams",
        "AIT": "Williams",
    },
    2019: {
        "HAM": "Mercedes",
        "BOT": "Mercedes",
        "VER": "Red Bull",
        "ALB": "Red Bull",
        "LEC": "Ferrari",
        "VET": "Ferrari",
        "RIC": "Renault",
        "HUL": "Renault",
        "NOR": "McLaren",
        "SAI": "McLaren",
        "PER": "Racing Point",
        "STR": "Racing Point",
        "RAI": "Alfa Romeo",
        "GIO": "Alfa Romeo",
        "GAS": "Toro Rosso",
        "KVY": "Toro Rosso",
        "MAG": "Haas",
        "GRO": "Haas",
        "FIT": "Haas",
        "RUS": "Williams",
        "KUB": "Williams",
    },
}

DRIVER_IDENTIFIER = {
    "HAM": "Lewis Hamilton",
    "BOT": "Valtteri Bottas",
    "VER": "Max Verstappen",
    "PER": "Sergio Pérez",
    "LEC": "Charles Leclerc",
    "SAI": "Carlos Sainz",
    "ALO": "Fernando Alonso",
    "OCO": "Esteban Ocon",
    "NOR": "Lando Norris",
    "RIC": "Daniel Ricciardo",
    "VET": "Sebastian Vettel",
    "STR": "Lance Stroll",
    "RAI": "Kimi Raikkkonen",
    "GIO": "Antonion Giovinazzi",
    "GAS": "Pierre Gasly",
    "TSU": "Yuki Tsunoda",
    "MSC": "Mick Schumacher",
    "MAZ": "Nikita Mazepin",
    "MAG": "Kevin Magnussen",
    "RUS": "George Russell",
    "LAT": "Nicolas Latifi",
}

DRIVER_NUMBERS = {
    2022: {
        "HAM": 44,
        "RUS": 63,
        "VER": 1,
        "PER": 11,
        "LEC": 16,
        "SAI": 55,
        "ALO": 14,
        "OCO": 31,
        "NOR": 4,
        "RIC": 3,
        "VET": 5,
        "VET": 27,
        "STR": 18,
        "BOT": 77,
        "ZHO": 24,
        "GAS": 10,
        "TSU": 22,
        "MAG": 20,
        "MSC": 47,
        "ALB": 23,
        "LAT": 6,
    },
    2021: {
        "HAM": 44,
        "BOT": 77,
        "VER": 1,
        "PER": 11,
        "LEC": 16,
        "SAI": 55,
        "ALO": 14,
        "OCO": 31,
        "NOR": 4,
        "RIC": 3,
        "VET": 5,
        "STR": 18,
        "RAI": 7,
        "GIO": 99,
        "KUB": 88,
        "GAS": 10,
        "TSU": 22,
        "MSC": 47,
        "MAZ": 9,
        "RUS": 63,
        "LAT": 6,
    },
    2020: {
        "HAM": 44,
        "BOT": 77,
        "VER": 33,
        "ALB": 23,
        "LEC": 16,
        "VET": 5,
        "RIC": 3,
        "OCO": 31,
        "NOR": 4,
        "SAI": 55,
        "PER": 11,
        "STR": 18,
        "HUL": 27,
        "RAI": 7,
        "GIO": 99,
        "GAS": 10,
        "KVY": 26,
        "MAG": 20,
        "GRO": 8,
        "FIT": 51,
        "RUS": 63,
        "LAT": 6,
        "AIT": 89,
    },
    2019: {
        "HAM": 44,
        "BOT": 77,
        "VER": 33,
        "GAS": 10,
        "ALB": 23,
        "LEC": 16,
        "VET": 5,
        "RIC": 3,
        "HUL": 27,
        "NOR": 4,
        "SAI": 55,
        "PER": 11,
        "STR": 18,
        "RAI": 7,
        "GIO": 99,
        "GAS": 10,
        "KVY": 26,
        "MAG": 20,
        "GRO": 8,
        "RUS": 63,
        "KUB": 88,
    },
    2018: {
        "HAM": 44,
        "BOT": 77,
        "VET": 5,
        "RAI": 7,
        "PER": 11,
        "OCO": 31,
        "VER": 33,
        "RIC": 3,
        "HUL": 27,
        "ALO": 14,
        "VAN": 2,
        "SAI": 55,
        "LEC": 16,
        "ERI": 9,
        "GAS": 10,
        "HAR": 28,
        "MAG": 20,
        "GRO": 8,
        "SIR": 35,
        "STR": 18,
    },
}

TEAM_ENGINES = {
    2021: {
        "Mercedes": "Mercedes",
        "Red Bull": "Honda",
        "McLaren": "Mercedes",
        "Aston Martin": "Mercedes",
        "Alpine": "Renault",
        "Ferrari": "Ferrari",
        "Alpha Tauri": "Honda",
        "Alfa Romeo": "Ferrari",
        "Haas": "Ferrari",
        "Williams": "Mercedes",
    },
    2020: {
        "Mercedes": "Mercedes",
        "Ferrari": "Ferrari",
        "Red Bull": "Honda",
        "McLaren": "Renault",
        "Renault": "Renault",
        "Alpha Tauri": "Honda",
        "Racing Point": "Mercedes",
        "Alfa Romeo": "Ferrari",
        "Haas": "Ferrari",
        "Williams": "Mercedes",
    },
}


class Round:
    def __init__(
        self, name, round_number, country, shortened_name, tire_compounds, track_name
    ):
        self.name = name
        self.round_number = round_number
        self.country = country
        self.shortened_name = shortened_name
        self.tire_compounds = tire_compounds
        self.track_name = track_name


CALENDAR = {
    2022: [
        Round(
            "Pre-Season Test",
            0,
            "Bahrain",
            "BAH",
            ["C5", "C4", "C3", "C2", "C1"],
            "Bahrain International Circuit",
        ),
        Round(
            "Bahrain Grand Prix",
            1,
            "Bahrain",
            "BAH",
            ["C3", "C2", "C1"],
            "Bahrain International Circuit",
        ),
        Round(
            "Saudi Arabian Grand Prix",
            2,
            "Saudi Arabia",
            "SAU",
            ["C4", "C3", "C2"],
            "Jeddah Corniche Circuit",
        ),
        Round(
            "Australian Grand Prix",
            3,
            "Australia",
            "AUS",
            ["C5", "C3", "C2"],
            "Melbourne Grand Prix Circuit",
        ),
        Round(
            "Emilia Romagna Grand Prix",
            4,
            "Italy",
            "EMI",
            ["C4", "C3", "C2"],
            "Autodromo Enzo e Dino Ferrari",
        ),
        Round(
            "Miama Grand Prix",
            5,
            "United States of America",
            "USA",
            ["C4", "C3", "C2"],
            "Miami International Autodrome",
        ),
        Round(
            "Spanish Grand Prix",
            6,
            "Spain",
            "ESP",
            ["C3", "C2", "C1"],
            "Circuit de Barcelona-Catalunya",
        ),
    ],
    2021: [
        Round(
            "Pre-Season Test",
            0,
            "Bahrain",
            "BAH",
            ["C5", "C4", "C3", "C2", "C1"],
            "Bahrain International Circuit",
        ),
        Round(
            "Bahrain Grand Prix",
            1,
            "Bahrain",
            "BAH",
            ["C4", "C3", "C2"],
            "Bahrain International Circuit",
        ),
        Round(
            "Emilia Romagna Grand Prix",
            2,
            "Italy",
            "EMI",
            ["C4", "C3", "C2"],
            "Autodromo Enzo e Dino Ferrari",
        ),
        Round(
            "Portuguese Grand Prix",
            3,
            "Portugal",
            "POR",
            ["C3", "C2", "C1"],
            "Autódromo Internacional do Algarve",
        ),
        Round(
            "Spanish Grand Prix",
            4,
            "Spain",
            "ESP",
            ["C3", "C2", "C1"],
            "Circuit de Barcelona-Catalunya",
        ),
        Round(
            "Monaco Grand Prix",
            5,
            "Monaco",
            "MON",
            ["C5", "C4", "C3"],
            "Circuit de Monaco",
        ),
        Round(
            "Azerbaijan Grand Prix",
            6,
            "Azerbaijan",
            "AZE",
            ["C5", "C4", "C3"],
            "Baku City Circuit",
        ),
        Round(
            "French Grand Prix",
            7,
            "France",
            "FRA",
            ["C4", "C3", "C2"],
            "Circuit Paul Ricard",
        ),
        Round(
            "Styrian Grand Prix",
            8,
            "Austria",
            "STY",
            ["C4", "C3", "C2"],
            "Red Bull Ring",
        ),
        Round(
            "Austrian Grand Prix",
            9,
            "Austria",
            "AUS",
            ["C5", "C4", "C3"],
            "Red Bull Ring",
        ),
        Round(
            "British Grand Prix",
            10,
            "United Kingdom",
            "GBR",
            ["C3", "C2", "C1"],
            "Silverstone Circuit",
        ),
        Round(
            "Hungarian Grand Prix",
            11,
            "Hungary",
            "HUN",
            ["C4", "C3", "C2"],
            "Hungaroring",
        ),
        Round(
            "Belgian Grand Prix",
            12,
            "Belgium",
            "BEL",
            ["C4", "C3", "C2"],
            "Circuit de Spa-Franchorchamps",
        ),
        Round(
            "Dutch Grand Prix",
            13,
            "Netherlands",
            "NLD",
            ["C3", "C2", "C1"],
            "Circuit Zandvoort",
        ),
        Round(
            "Italian Grand Prix",
            14,
            "Italy",
            "ITA",
            ["C4", "C3", "C2"],
            "Autodromo Nazionale di Monza",
        ),
        Round(
            "Russian Grand Prix",
            15,
            "Russia",
            "RUS",
            ["C5", "C4", "C3"],
            "Sochi Autodrom",
        ),
        Round(
            "Turkish Grand Prix",
            16,
            "Turkey",
            "TUR",
            ["C4", "C3", "C2"],
            "Istanbul Park",
        ),
        Round(
            "United States Grand Prix",
            17,
            "United States of America",
            "USA",
            ["C4", "C3", "C2"],
            "Circuit of the Americas",
        ),
        Round(
            "Mexico City Grand Prix",
            18,
            "Mexico",
            "MEX",
            ["C4", "C3", "C2"],
            "Autódromo Hermanos Rodríguez",
        ),
        Round(
            "São Paulo Grand Prix",
            19,
            "Brazil",
            "BRA",
            ["C4", "C3", "C2"],
            "Autodromo José Carlos Pace",
        ),
        Round(
            "Qatar Grand Prix",
            20,
            "Qatar",
            "QAT",
            ["C4", "C3", "C2"],
            "Losail International Circuit",
        ),
        Round(
            "Saudi Arabian Grand Prix",
            21,
            "Saudi Arabia",
            "SAU",
            ["C4", "C3", "C2"],
            "Jeddah Corniche Circuit",
        ),
        Round(
            "Abu Dhabi Grand Prix",
            22,
            "United Arab Emirates",
            "UAE",
            ["C5", "C4", "C3"],
            "Yas Marina Circuit",
        ),
    ]
}

TRACK_LENGTHS = {
    "Bahrain Grand Prix": 5.412,
    "Emilia Romagna Grand Prix": 4.909,
    "Portuguese Grand Prix": 4.673,
    "Spanish Grand Prix": 4.675,
    "Monaco Grand Prix": 3.337,
    "Azerbaijan Grand Prix": 6.003,
    "French Grand Prix": 5.842,
    "Styrian Grand Prix": 4.318,
    "Austrian Grand Prix": 4.318,
    "British Grand Prix": 5.891,
    "Hungarian Grand Prix": 4.381,
    "Belgian Grand Prix": 7.004,
    "Dutch Grand Prix": 4.259,
    "Italian Grand Prix": 5.793,
    "Russian Grand Prix": 5.848,
    "Turkish Grand Prix": 5.338,
    "United States Grand Prix": 5.513,
    "Mexico City Grand Prix": 4.304,
    "São Paulo Grand Prix": 4.309,
    "Qatar Grand Prix": 5.380,
    "Saudi Arabian Grand Prix": 6.174,
    "Abu Dhabi Grand Prix": 5.281,
}

SESSION_TRANSLATE = {
    "1": "Day 1",
    "2": "Day 2",
    "3": "Day 3",
    "FP1": "Pracice 1",
    "FP2": "Practice 2",
    "FP3": "Practice 3",
    "Q": "Qualifying",
    "SQ": "Sprint Qualifying",
    "R": "Race",
    "": "",
}


TIRE_COMPOUND_COLORS = {
    "SOFT": "#F52A29",
    "MEDIUM": "#FFD411",
    "HARD": "#FFFFFF",
    "INTERMEDIATE": "#3AC82C",
    "WET": "#0088FF",
}

DRS_STATES = {
    0: "Closed",
    1: "Disallowed",
    8: "In Range",
    12: "Engaged",
    14: "Available",
}

SECTOR_COLORS = {
    1: "#F90505",
    2: "#06B4E6",
    3: "#F6D005",
}

TRACKS_SECTIONS = {
    "Bahrain International Circuit": {
        0: "",
        9.5: "T1",
        14.3: "T2",
        16.5: "t3",
        18.2: "",
        25: "T4",
        31.5: "T5",
        33.5: "T6",
        36: "T7",
        39: "T8",
        44: "",
        46.5: "T9",
        49: "T10",
        52.5: "",
        60.2: "T11",
        66: "T12",
        73: "T13",
        77.8: "",
        88: "T14",
        91.8: "T15",
        94: "",
    },
    "Melbourne Grand Prix Circuit": {
        0: "",
    },
    "Autodromo Enzo e Dino Ferrari": {
        0: "",
        3.7: "t1",
        15.5: "T2",
        19: "T3",
        21: "T4",
        24: "",
        30: "T5",
        32.3: "T6",
        36.5: "T7",
        40.8: "",
        47: "t8",
        49.5: "T9",
        53: "t10",
        56: "",
        59.4: "T11",
        61.3: "T12",
        63.1: "T13",
        64.2: "",
        69.8: "T14",
        72.8: "T15",
        75: "",
        84.2: "t16",
        85: "",
        86: "T17",
        89.6: "T18",
        92.5: "",
        97.5: "t19",
        98.5: "",
    },
    "Autódromo Internacional do Algarve": {
        0: "",
        11: "T1",
        16.3: "T2",
        18.6: "T3",
        22.8: "T4",
        26: "",
        33: "T5",
        38.6: "",
        41: "t6",
        43.1: "",
        45.4: "T7",
        48: "T8",
        52.5: "",
        56.1: "t9",
        58.5: "",
        61.2: "T10",
        62.6: "T11",
        65.3: "",
        69: "t12",
        71: "T13",
        76: "T14",
        82: "",
        87: "T15",
        90: "",
    },
    "Circuit de Barcelona-Catalunya": {
        0: "",
        14.7: "T1",
        19: "T2",
        21.5: "T3",
        31.3: "",
        33.6: "T4",
        41: "",
        42.5: "T5",
        47.2: "",
        50: "T6",
        52: "T7",
        55.8: "T8",
        60.1: "T9",
        71.2: "T10",
        77: "T11",
        78.5: "T12",
        84: "T13",
        87.3: "T14",
        89.4: "T15",
        92: "T16",
        95.5: "",
    },
    "Circuit de Monaco": {
        0: "",
        1.8: "T1",
        9.5: "",
        17: "t2",
        18.3: "T3",
        24.8: "T4",
        30: "T5",
        35.5: "T6",
        38.5: "T7",
        40.8: "T8",
        44.7: "",
        51: "t9",
        52.5: "",
        58.5: "T10",
        63: "T11",
        68.5: "T12",
        73.8: "T13",
        76: "T14",
        77.5: "T15",
        81.5: "T16",
        84: "T17",
        84.3: "T18",
        88.2: "T19",
        92.5: "",
    },
    "Baku City Circuit": {
        0: "",
        1.8: "T1",
        6.5: "",
        8.4: "T2",
        12.3: "",
        21.8: "T3",
        26.8: "T4",
        32.2: "T5",
        35.2: "T6",
        39: "T7",
        44.2: "T8",
        45.9: "T9",
        46.1: "T10",
        46.3: "T11",
        47.8: "T12",
        50: "",
        54.3: "t13",
        55.8: "",
        58: "t14",
        59: "T15",
        65: "T16",
        71: "T17",
        72.5: "",
        75.4: "t18",
        77.4: "t19",
        84.2: "t20",
    },
    "Circuit Paul Ricard": {
        0: "",
        4.9: "T1",
        8.7: "T2",
        12: "",
        17: "T3",
        19.8: "T4",
        21.5: "T5",
        23.5: "T6",
        28: "T7",
        45: "T8",
        48.2: "T9",
        50.9: "",
        62: "T10",
        67.5: "T11",
        76.5: "T12",
        83: "T13",
        85.3: "T14",
        89.5: "T15",
        92.8: "",
    },
    "Red Bull Ring": {
        0: "",
        6.3: "T1",
        12.3: "",
        25.1: "T2",
        25.8: "",
        27.9: "t3",
        35: "",
        46.7: "T4",
        53.5: "T5",
        59.3: "T6",
        66.8: "T7",
        74: "T8",
        77.5: "",
        84.45: "T9",
        89.5: "T10",
    },
    "Silverstone Circuit": {
        0: "",
        5.6: "T1",
        9.3: "T2",
        12.3: "T3",
        16.1: "T4",
        19.6: "T5",
        23: "",
        30.8: "T6",
        34.9: "T7",
        39.3: "",
        43: "t8",
        44: "",
        50.1: "T9",
        54.5: "",
        59.5: "T10",
        61.6: "T11",
        64.1: "T12",
        66.6: "T13",
        70.5: "t14",
        72.8: "",
        82.5: "T15",
        91: "T16",
        94.4: "T17",
        97.1: "T18",
    },
    "Hungaroring": {
        0: "",
        10.5: "T1",
        17.5: "",
        22.5: "T2",
        29.1: "T3",
        32.6: "",
        38.8: "T4",
        43.8: "T5",
        51.8: "T6",
        55.2: "T7",
        57.5: "T8",
        60.9: "T9",
        65.3: "T10",
        68.8: "T11",
        73.5: "",
        77.2: "T12",
        83.5: "T13",
        90: "T14",
        97.8: "",
    },
    "Circuit de Spa-Franchorchamps": {
        0: "",
        2.5: "T1",
        7.5: "",
        14.7: "T2",
        15.6: "T3",
        17.5: "T4",
        19.5: "",
        31: "T5",
        35.1: "T6",
        36.7: "T7",
        39.1: "",
        40.5: "T8",
        45.5: "T9",
        48.5: "",
        52.5: "T10",
        56.6: "T11",
        60: "",
        61.4: "T12",
        65.5: "T13",
        68.4: "T14",
        72.5: "T15",
        77: "",
        84.5: "t16",
        85: "",
        87.5: "T17",
        90.3: "",
        92.7: "T18",
        96.8: "T19",
        98.5: "",
    },
    "Circuit Zandvoort": {
        0: "",
        4.6: "T1",
        13.9: "T2",
        17.1: "T3",
        22: "",
        24.5: "t4",
        25.5: "",
        28.8: "t5",
        32.5: "t6",
        36.3: "T7",
        43.5: "T8",
        49.9: "T9",
        55.6: "T10",
        62.5: "",
        69.1: "T11",
        73.2: "T12",
        79.7: "T13",
        83.9: "",
        89: "t14",
        90.5: "",
    },
    "Autodromo Nazionale di Monza": {
        0: "",
        12.7: "T1",
        16.2: "T2",
        18.7: "",
        21: "t3",
        22: "",
        33.7: "T4",
        37.2: "T5",
        41.1: "T6",
        47.2: "T7",
        51.0: "",
        65.2: "T8",
        68.7: "T9",
        70.7: "T10",
        73: "",
        85.8: "T11",
        93: "",
    },
    "Sochi Autodrom": {
        0: "",
        7: "t1",
        9: "",
        17.85: "T2",
        23.5: "t3",
        33: "T4",
        37: "",
        40.6: "T5",
        46.5: "t6",
        48.1: "T7",
        53.6: "T8",
        56.6: "T9",
        59.7: "T10",
        64: "",
        67: "t11",
        68: "",
        75: "t12",
        78.5: "T13",
        82.3: "T14",
        85.3: "T15",
        88.4: "T16",
        93.4: "T17",
        96.7: "T18",
    },
    "Istanbul Park": {
        0: "",
        5.6: "T1",
        10.5: "t2",
        19.6: "T3",
        23.4: "T4",
        26.2: "T5",
        29.5: "T6",
        32: "",
        35.9: "T7",
        45.8: "T8",
        56: "",
        61.9: "T9",
        66.1: "T10",
        68.9: "",
        76: "t11",
        78: "",
        87.1: "T12",
        92.1: "T13",
        94: "T14",
        98: "",
    },
    "Circuit of the Americas": {
        0: "",
        8.8: "T1",
        14.3: "t2",
        20.5: "T3",
        22.3: "T4",
        23.8: "T5",
        25.3: "T6",
        29.7: "T7",
        32.3: "T8",
        35: "T9",
        37.3: "",
        38.8: "t10",
        40.2: "",
        43.15: "T11",
        65.7: "T12",
        70.5: "T13",
        73.5: "T14",
        75.2: "T15",
        79.8: "T16",
        82.5: "T17",
        85.8: "t18",
        89.1: "T19",
        94.6: "T20",
        99.5: "",
    },
    "Autódromo Hermanos Rodríguez": {
        0: "",
        23.8: "T1",
        29.2: "T2",
        30.9: "T3",
        35: "",
        43.9: "T4",
        48.5: "T5",
        51: "T6",
        58: "T7",
        62: "T8",
        63.85: "T9",
        66.6: "T10",
        70.7: "T11",
        76: "",
        81.3: "T12",
        86.7: "T13",
        89.9: "T14",
        91: "T15",
        91.65: "T16",
        96.5: "T17",
    },
    "Autodromo José Carlos Pace": {
        0: "",
        4.3: "T1",
        9.8: "T2",
        12.7: "T3",
        19.2: "",
        30: "T4",
        36: "T5",
        39: "",
        44.8: "T6",
        49: "T7",
        52: "T8",
        56.15: "T9",
        60.7: "T10",
        67.2: "t11",
        72.5: "T12",
        78: "",
        79: "t13",
        81.5: "t14",
        85: "t15",
        88: "",
    },
    "Losail International Circuit": {
        0: "",
        5.8: "T1",
        12.7: "T2",
        18: "",
        18.4: "t3",
        24.6: "T4",
        28.5: "T5",
        32.8: "T6",
        40.15: "T7",
        46.3: "T8",
        48.2: "T9",
        50.6: "T10",
        56: "t11",
        63.1: "T12",
        66.8: "T13",
        70.2: "T14",
        75.9: "T15",
        83.6: "T16",
        90: "",
    },
    "Jeddah Corniche Circuit": {
        0: "",
        5.5: "T1",
        8.4: "T2",
        10: "t3",
        12: "",
        14.5: "T4",
        16.8: "T5",
        20.0: "T6",
        22.2: "T7",
        23.2: "T8",
        24.6: "T9",
        26.9: "T10",
        28.6: "T11",
        30.5: "t12",
        32: "",
        36.5: "T13",
        41.5: "",
        44: "t14",
        46: "",
        48: "T15",
        49.5: "T16",
        50.8: "T17",
        53.1: "t18",
        57.0: "t19",
        60: "t20",
        64.5: "t21",
        67.5: "T22",
        70.9: "T23",
        72.5: "T24",
        76: "t25",
        83: "t26",
        87.5: "T27",
        91.7: "",
    },
    "Yas Marina Circuit": {
        0: "",
        4.9: "T1",
        11.2: "T2",
        14.2: "T3",
        19: "t4",
        24.05: "T5",
        30.5: "",
        47.3: "T6",
        50.75: "T7",
        54: "t8",
        66.8: "T9",
        76.8: "T10",
        79.5: "T11",
        80.2: "T12",
        83.8: "T13",
        85.75: "T14",
        91: "T15",
        94.3: "T16",
    },
}
